// File generated by FlutterFire CLI.
// This is a placeholder file. Run 'flutterfire configure --platforms=android,ios' to generate the actual configuration.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// This app supports only iOS and Android platforms.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'This app only supports iOS and Android platforms. '
          'DefaultFirebaseOptions have not been configured for ${defaultTargetPlatform.name}.',
        );
    }
  }

  // TODO: Replace with your Firebase project configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ZAPRv2A7qMmeKifuwvdMpbkUqomdTS4',
    appId: '1:628765909477:android:b608e6ccf0b499e9c00f0c',
    messagingSenderId: '628765909477',
    projectId: 'hotel-booking-9baa3',
    storageBucket: 'hotel-booking-9baa3.firebasestorage.app',
  );

  // Run 'flutterfire configure --platforms=android,ios' to generate these values

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJCLCljYfPyy4KmAGT0mThHz1uVecJA4g',
    appId: '1:628765909477:ios:c9dd13ab7c6b16a0c00f0c',
    messagingSenderId: '628765909477',
    projectId: 'hotel-booking-9baa3',
    storageBucket: 'hotel-booking-9baa3.firebasestorage.app',
    iosBundleId: 'com.example.myBlocApp',
  );

}